### ISSUE TITLE
Content with Guid "xxx" was not found

### ISSUE THREAD

**Issue by ovelartelius** [LinusEkstrom/AddOn.Episerver.Settings#13]
When we run a project against a new database, but with code with existing settings, we get this error message when start the site for the first time.

Exception Details: EPiServer.Core.ContentNotFoundException: Content with Guid "a5c22695-fb6f-493e-842f-6c214f5d63bf" was not found
[ContentNotFoundException: Content with Guid "a5c22695-fb6f-493e-842f-6c214f5d63bf" was not found]
   EPiServer.Core.Internal.DefaultContentLoader.Get(Guid contentGuid, LoaderOptions loaderOptions) +162
   EPiServer.Core.Internal.DefaultContentLoader.Get(Guid contentGuid) +86
   EPiServer.Core.Internal.DefaultContentRepository.Get(Guid contentGuid) +77
   AddOn.Episerver.Settings.Core.SettingsService.InitializeContentInstances() +483
   AddOn.Episerver.Settings.Core.SettingsService.InitSettings() +419
   AddOn.Episerver.Settings.Core.SettingsInitializationModule.InitCompleteHandler(Object sender, EventArgs e) +14
![image](https://user-images.githubusercontent.com/4722784/93390067-63efb900-f86d-11ea-822b-a455968e84fe.png)

The setting that I can find in the code is:
[SettingsContentType(
	    AvailableInEditMode = false,
	    GUID = "2eec1957-8590-48f4-becd-7febf594a162",
	    SettingsName = "Cdn Cache Settings",
	    SettingsInstanceGuid = "a5c22695-fb6f-493e-842f-6c214f5d63bf")]
    public class CdnCacheSettings : SettingsBase
    {
        [Display(GroupName = SystemTabNames.Content, Order = 100)]
        public virtual int CacheDurationInMinutes { get; set; }
    }

![image](https://user-images.githubusercontent.com/4722784/93390147-884b9580-f86d-11ea-8dad-55fff43c0e83.png)

Can we do something to handle this? Or does the method AddOn.Episerver.Settings.Core.SettingsService.InitializeContentInstances need a extra TryCatch to handle this?

**Comment by LinusEkstrom** [comment]
Thanks for reporting, will fix ASAP.

**Comment by LinusEkstrom** [comment]
This was actually fixed a few months back, but the nuget posted to Episerver did not have the fix in it.
