### ISSUE TITLE
Global commerce settings

### ISSUE THREAD

**Issue by stibay** [LinusEkstrom/AddOn.Episerver.Settings#27]
Not sure if I am doing something wrong but it seems like there is a bug when using a commerce ui hint on a global setting.

If I f.ex have this setting I can add it to a page but when I try to add this as a global setting

[UIHint(EPiServer.Commerce.UIHint.CatalogNode)]
public virtual ContentReference SomeCatalogRef { get; set; }

This error show ups in the console - No store by the name 'epi.commerce.relation' 

But it works fine as a local setting and also if I add the global setting on a page.

I also dont quite get the guid's on the global setting. For both of them to show up I need to have the GUID on SettingClass2 to be the same as SettingsInstanceGuid on SettingClass1

I understood it as the SettingsInstanceGuid would be the same on the global setting classes and the GUID on the global settings classes should be unique?

- Episerver CMS 12.4.2
- Episerver Commerce 14.1.3

**Comment by LinusEkstrom** [comment]
Hi Stian,

As for the commerce properties, I guess that no one has actually tried this before. It seems like the editor widget has a dependency to a REST store that is probably set up by a shell module, but this is not done on demand. I can create a bug for this, but we'll have to discuss urgency/who can adress this separately.

As for the GUIDs, each settings type should have it's GUID - just as any other content type. What's unique for global settings is the SettingsInstanceGuid property, which ensures that the system can use or create (on demand) a singleton instance of the settings type.

**Comment by vansterhant** [comment]
@stibay, could you find the time to verify that bug has been solved? The nuget containing the fix can be downloaded here:https://github.com/LinusEkstrom/AddOn.Episerver.Settings/suites/6427622740/artifacts/234948845

**Comment by stibay** [comment]
@vansterhant Yes, I will do that. Thanks alot for fixing this. We had to move away from this since we also found it abit hard to manage the settings content that got created because the content types is not showing up in the new episerver admin GUI so if we deleted or renamed classes we feared it could be dificult to clean these up after its deployed to DXP. Noticed alot of the Bootstrap error localy which required manually finding the ids of the content and manually removing it from the DB.

**Comment by vansterhant** [comment]
@stibay Thanks!

And yes, that is a problem. There is a workaround documented in the readme (https://github.com/LinusEkstrom/AddOn.Episerver.Settings#removing-settings-classes). 

Performing that update on the db will ensure there are no problems going forward with removed settings-classes since Episerver then can load content that is no longer backed by a class.

There is a bug reported about that the server does not update the "base" column by itself, which (if I understood correctly) was the intended behaviour.
