### ISSUE TITLE
Sidebar Gadget does not appear

### ISSUE THREAD

**Issue by ethanschofer** [LinusEkstrom/AddOn.Episerver.Settings#34]
After installing the NuGet package, the sidebar gadget does not appear. Is this a config step I am missing? This is AMS version 12.6. Im not sure what other packages might affect this?

**Comment by vansterhant** [comment]
No, there is no further configuration needed. The gadget should appear automatically in the group with blocks and media.

![settings](https://user-images.githubusercontent.com/1822129/169778438-c0404635-cca9-4e67-9d72-3252b1f89245.png)

(screenshot from a vanilla CMS 12.6 alloy template site)

**Comment by LinusEkstrom** [comment]
Gadgets are only plugged in for areas (aka a sidebar) that has not been customized by the user (aka editor). Try resetting your views in your editorial settings and see if it appears then or if you still have a problem with this.

**Comment by LinusEkstrom** [comment]
Was this resolved @ethanschofer?

**Comment by ethanschofer** [comment]
I'm not sure. I rolled my own solution. I do have a much better understanding of plug ins now, so it's possible I could make it work? But I haven't tried

Ethan

**Comment by LinusEkstrom** [comment]
Ok, closing this issue then for now.
