### ISSUE TITLE
removing old settings

### ISSUE THREAD

**Issue by natbredenkamp** [LinusEkstrom/AddOn.Episerver.Settings#36]
is there a way to remove unused old settings?
We don't have access to the database, so cant follow the steps at the end of the read me. We had added a setting on one of the global settings pages and have since removed it, but it is still there and not only will not remove, but stops other settings on that 'page' from being updated.
cant do the usual thing of going to the contentTypes and deleting properties where FromCode  is No
also getting this intermittently
The view 'Bootstrapper' was not found. Searched locations: ["AddOn.Episerver.Settings.Views/Views/DefaultShellModule/Bootstrapper.cshtml","/CmsDefault/AddOn.Episerver.Settings.Views/Views/DefaultShellModule/Bootstrapper.cshtml","AddOn.Episerver.Settings.Views/Views/Shared/Bootstrapper.cshtml","/CmsDefault/AddOn.Episerver.Settings.Views/Views/Shared/Bootstrapper.cshtml","AddOn.Episerver.Settings.Views/Pages/Shared/Bootstrapper.cshtml","/CmsDefault/AddOn.Episerver.Settings.Views/Pages/Shared/Bootstrapper.cshtml","AddOn.Episerver.Settings.Views/Util","/CmsDefault/AddOn.Episerver.Settings.Views/Util"]

**Comment by vansterhant** [comment]
There was previously a bug (https://world.optimizely.com/support/Bug-list/bug/CMS-21725) that made it impossible to solve without manually editing the database. Bu if you are on EPiServer.CMS.Core 12.4.1 or newer it is possible to drop no longer existing settings-content-types by:

0. Remove the settings-class
1. In the global settings, right click on the setting to remove, "move to trash"
2. In CMS edit trash view, delete the setting
3. Restart the site, this will autmatically clean content types that no longer have backing code or instances

![image](https://user-images.githubusercontent.com/1822129/185073925-875ef002-ef49-48df-924a-aa6f096820f4.png)

**Comment by LinusEkstrom** [comment]
Have you tried the suggestion above @natbredenkamp yet? Want to see if we can close this ticket...

**Comment by LinusEkstrom** [comment]
Closing ticket due to not getting a response.

**Comment by LinusEkstrom** [comment]
Thanks for the additional @Nettsentrisk. We'll investigate to see if this can be done with a reasonable effort.
