### ISSUE TITLE
Error looking for Bootstrapper.cshtml

### ISSUE THREAD

**Issue by natbredenkamp** [LinusEkstrom/AddOn.Episerver.Settings#37]
When attempting to view the Global Settings page, it throws an error - the view 'Bootstrapper' was not found, reeling off the list of places its searched.
Seems to be the DefaultShellModuleController Index method that is returning the Bootstrapper view name that is causing it to fail.
This happens every time when the Global settings page is the first thing accessed after a site restart (locally), and seems to happen intermittently at other times (on DXP). 
It kills the site and it then needs restarting, doesn't matter if you try to load some other page afterwards.

**Comment by LinusEkstrom** [comment]
@vansterhant : Perhaps something that you can look into when you are back from vacation?

**Comment by LinusEkstrom** [comment]
Thanks for reporting Nat. Most of us working with this have been on vacation, but we'll look into this soon.

**Comment by vansterhant** [comment]
Nice find! 
This unfortunately seems to be a bug in the CMS itself (If the first request is for a module, the search for the Bootstrapper view is scoped to within the module, AND the "no view found"-result is cached...) so I can't find a (reasonable) way to solve it from the settings module. 

I'm communicating with Optimizely support, to get a bug registered so that this can get fixed.

**Comment by vansterhant** [comment]
The bug has now been reported to Optimizely and is trackable by the id: **CMS-24678**

**Comment by LinusEkstrom** [comment]
Hi @vansterhant . I tried finding the bug mentioned above in the Optimizely bug list but I get an error that this bug does not exist. Can you verify if this is the right ID and if you can find it?

**Comment by vansterhant** [comment]
It may still be in triage, I received emails this week regarding follow-up questions from the dev-team on what we are trying to achieve by using ICustomView et. al

**Comment by vansterhant** [comment]
The bug has gotten a new id:
https://world.optimizely.com/support/bug-list/bug/CMS-25276

**Comment by LinusEkstrom** [comment]
This bug has now been tagged as fixed and release in EPiServer.CMS.UI 12.16.0. Will evaluate if this fixes the problem once the package has been released.

**Comment by LinusEkstrom** [comment]
@vansterhant EPiServer.CMS.UI 12.16.0 is now available. Can you give this a test to see if we can close this issue?

**Comment by vansterhant** [comment]
CMS 12.16.0 solves the issue. Finally closing this.

**Comment by LinusEkstrom** [comment]
*throwing confetti in the air :)*
