### ISSUE TITLE
Request: Add blocks gadget to global settings view

### ISSUE THREAD

**Issue by reneemhaas-diagram** [LinusEkstrom/AddOn.Episerver.Settings#41]
It would be nice to have view of a blocks gadget (along side where versions gadget is now) so that blocks can be dropped into global settings content areas.

**Comment by LinusEkstrom** [comment]
Sounds like a reasonable request. @vansterhant : Is this something that you can look into?

**Comment by vansterhant** [comment]
Should be a fairly easy to add (famous last words...)
