### ISSUE TITLE
Proposal: Change default behaviour of GetSettings without parameter to take the current context and add possibility to get list of settings

### ISSUE THREAD

**Issue by LinusEkstrom** [LinusEkstrom/AddOn.Episerver.Settings#56]
Today, the default behavior when fetching settings without sending in the current content is to fetch settings from the global settings repository. We've gotten feedback that the most common case is to want to fetch settings that are specific for the current content item.

I suggest that we change the behaviour of the GetSettings method to automatically use the current content context and instead have a specific method for fetching global settings and bypassing the logic based on the logic tree. The method with sending in a specific content object can still be kept.

Perhaps we can combine this with changing the name/sygnature of the method for better clarity and also introduce the ability to fetch all potential settings upwards in the content tree. This would enable settings that could override parts of each other to build a dynamic object.

GetSetting() //Automatically fetches the current content object and traverses the content tree with fallback to global settings.
GetSetting(contentReference) //Uses the specified content object and traverses the content tree with fallback to global settings.
GetGlobalSetting();

IEnumerable<type>GetSettings(contentReference) //Uses the specified content object and traverses the content tree with fallback to global settings and return all valid settings in sorted order closest setting first in the list.

**Comment by LinusEkstrom** [comment]
What do you think about this suggestion @toregjerdrum @jstemerdink @vansterhant ?

**Comment by vansterhant** [comment]
Sounds reasonable, being expilicit about what is going to happen i usually a good idea.

Do you propose we change the signature for the getSetting to take a ContentReference as input? Right now it expects IContent: 
public T GetSettings<T>(IContent content)

**Comment by LinusEkstrom** [comment]
Good question @vansterhant. I would potentially feel that a content reference is more appropriate even though I don't have strong opinions.

**Comment by LinusEkstrom** [comment]
@vansterhant : Feel free to start with a PR for this change whenever you have time. Since we just released 4.0 publically we probably need to decide if we call this 5.0 or just sneak it out before 4.0 get's wider adoptation.
