### ISSUE TITLE
Do not see "commerce" assets pane

### ISSUE THREAD

**Issue by VaclavRoncka** [LinusEkstrom/AddOn.Episerver.Settings#71]
Hi, 
is it possible to see the Commerce assets pane when using this settings addon?
How to set it up?
Thank you :)
![image](https://github.com/LinusEkstrom/AddOn.Episerver.Settings/assets/15107014/021a6a62-c9a4-44b2-a2e8-63fe541e70d7)

**Comment by LinusEkstrom** [comment]
@vansterhant Do you know what's needed to be able to add cms and commerce gadgets in the "add gadgets" dialog?

**Comment by vansterhant** [comment]
hmm, I'm guessing a bit, but it can be the filtering categories that is supplied to the dialog. 

looking at the code for the global view, there is nothing set for ComponentCategories
<img width="497" alt="image" src="https://github.com/LinusEkstrom/AddOn.Episerver.Settings/assets/1822129/678953a1-bc68-42ab-a794-b5649102b2e3">
with a bit of luck updating that property with some magic strings would allow the dialog to show a selection of gadgets?!

**Comment by vansterhant** [comment]
@LinusEkstrom did an investigation and by adding some categories and making the right pane into a user customizable version it is possible to manually add gadgets. Have a look at the commit above. 
The question is if/which drawbacks there are to storing personalized data for this view?

**Comment by LinusEkstrom** [comment]
I don't see any problem with that @vansterhant as long as you still can reset the view.

**Comment by LinusEkstrom** [comment]
Hi @VaclavRoncka . We've built a new version with the support to add gadgets in the side bar, in the same way that it works in the CMS view. Once the new version has been accepted to the Optimizely Nuget feed you should be able to test this out.

**Comment by LinusEkstrom** [comment]
@VaclavRoncka Great to hear, and thank you for the great report that was easy to understand. This addon has been built brick by brick during almost 10 years now by small additions like this :)

**Comment by VaclavRoncka** [comment]
Hello, I just tested the "latest" nuget version and:
Your change enabled the possibility to add "gadgets" (it was originally "empty") which is great!
But there is still no "catalogs" menu => missing the possibility to drag and drop "commerce" content to the settings :(

![image](https://github.com/LinusEkstrom/AddOn.Episerver.Settings/assets/15107014/3f46768b-dad2-4e99-a104-349eb9f32401)
