### ISSUE TITLE
IList<Block> does not work

### ISSUE THREAD

**Issue by otanum** [LinusEkstrom/AddOn.Episerver.Settings#74]
When using IList<Block> on Settings no block properties are shown.

Ref: https://world.optimizely.com/blogs/bartosz-sekula/dates/2023/1/official-list-property-support

Steps to reproduce:

**1) Add a simple block**
[ContentType(AvailableInEditMode = false, GUID = "<guid>")] 
public class PersonBlock : BlockData
{    
    public virtual string FirstName { get; set; }
    public virtual string LastName { get; set; }
}

**2) Add list property to settings**
public virtual IList<PersonBlock> Persons { get; set; }

**3) Try to add PersonBlocks**
FirstName and LastName properties are not displayed. Works if IList<PersonBlock> are added to Page.

**Comment by otanum** [comment]
@vansterhant  @LinusEkstrom 

Any update available for this issue?

**Comment by vansterhant** [comment]
@otanum I have done some further tinkering/debugging (mainly by trying different variants of add ISecurable to the Settings) to see if there was a way to pass the security-check for the ui-tabs, but without success.

I will open up a support case with Optimizely to see if they can help out with a way to get it working. 
Most likely our use case is an unforeseen scenario, so it may require a fix in the Optimizely code base to get it working.

**Comment by LinusEkstrom** [comment]
@vansterhant Did you get any response from Optimizely regarding the potential issue in the platform?

**Comment by barteksekula** [comment]
@LinusEkstrom Hi, we refactored the code a bit so we can fix this issue.
https://world.optimizely.com/documentation/Release-Notes/ReleaseNote/?releaseNoteId=CMS-30438

In order to fix the issue you see here you will need to implement IContentSecurable in your custom class which inherits from SettingsBase.

```c#
[SettingsContentType(AvailableInEditMode = false, GUID = "15506171-c6b2-4a7a-9c44-bb870f695911", SettingsInstanceGuid = "d8701e64-8206-4e24-bd3f-cb02b875d6c6", SettingsName = "MySettings")]
public class MySettings: SettingsBase, IContentSecurable
{
	private readonly Injected<IContentLoader> _contentLoader;

	public virtual IList<PersonBlock> Persons { get; set; }
	public ISecurityDescriptor GetSecurityDescriptor()
	{
		return GetContentSecurityDescriptor();
	}

	public IContentSecurityDescriptor GetContentSecurityDescriptor()
	{
		// return any list of valid ACL, for example from Root or StartPage which those settings belong to
		var accessControlList = (_contentLoader.Service.Get<IContent>(ContentReference.StartPage) as PageData).ACL;
		return (IContentSecurityDescriptor)accessControlList.CreateWritableClone();
	}
}
```

**Comment by LinusEkstrom** [comment]
@vansterhant Since you have been investigating this before, perhaps you can review @barteksekulas solution above to see if you think it's valid.
