### ISSUE TITLE
Issues with Opti ID

### ISSUE THREAD

**Issue by andrewmarkham** [LinusEkstrom/AddOn.Episerver.Settings#76]
Hi,

The module fails to load once Opti ID is enabled, the URL is kept at episerver, rather than changing to UI.

**Get**:
https://localhost:5000/episerver/AddOn.Episerver.Settings/settings

**Expect**:
https://localhost:5000/ui/AddOn.Episerver.Settings/settings

I have hacked with a redirect, but this seems to cause the left hand menu to not load.

![image](https://github.com/LinusEkstrom/AddOn.Episerver.Settings/assets/11081193/e93d01fb-2210-4753-b304-77c805db3e33)

**Comment by LinusEkstrom** [comment]
Hi @andrewmarkham . Thanks for submitting a fix for your issue. I've uploaded a new version of the package including your fix to the Optimizely feed, so just waiting for approval. However, I want to mention that I uploaded another minor version earlier this week, and we've had one report of an issue that seems to be caused to this change that was proposed by developers from the Optimizely core team to fix a long standing issue. If you want to speed things up, you can test the new version and get back to me if you get any issues or not.

**Comment by andrewmarkham** [comment]
Hi @LinusEkstrom,

I can take a look, can you just confirm the branch I should be using to test, and what the specific issue is I am looking for.

Thanks

**Comment by andrewmarkham** [comment]
Hi @LinusEkstrom, I thought this version of the package had been pulled based on your comment and we also had issues with the build.  But it turns out that the opti nuget repos are out of sync, there are currently two:

- https://api.nuget.optimizely.com/packages/addon.episerver.settings
- https://nuget.optimizely.com/package/?id=AddOn.Episerver.Settings

I am not 100% sure why these have got out of sync.

**Comment by LinusEkstrom** [comment]
@andrewmarkham Could you test this issue as well with the latest version to see if this also got fixed as expected?

**Comment by andrewmarkham** [comment]
@LinusEkstrom This is working, thanks
