### ISSUE TITLE
Site fails to start is there isn't a wildcard in the site definition.

### ISSUE THREAD

**Issue by andrewmarkham** [LinusEkstrom/AddOn.Episerver.Settings#80]
With the latest version (5.1.2), the website fails to start and throws an error (see below)

![image](https://github.com/user-attachments/assets/c3d2c63d-8af8-40c5-9180-574658cf2f7d)

This only happens when the site isn't configured with a wildcard hostname.  The issue occurs in the code snippet below.

<img width="1064" alt="image" src="https://github.com/user-attachments/assets/723dbe19-0184-456a-a78c-b37e2e0de58f">

I think the fix may be to check to see if the StartPage is an EmptyReference, and if so, fall back to the RootPage.

**Comment by LinusEkstrom** [comment]
Hi @andrewmarkham . Thanks for the report. We just made a fix for this and will do some testing on a few solutions before pushing a new version to the Optimizely Nuget feed - hopefully later today.

**Comment by andrewmarkham** [comment]
Hi @LinusEkstrom,

I have updated the code to use the latest version and I am still getting the error.  This happens on site startup during the model sync.

The updated code still fails on the same line as when you try an get a page with an emptyreference the method throws an exception, rather than retuning a null.

I think the code should check the content reference first.

```
    public IContentSecurityDescriptor GetContentSecurityDescriptor()
    {
        // Fallback to the root page if the wildcard isn't set for the site hostname
        var aclReference = ContentReference.StartPage == ContentReference.EmptyReference ? ContentReference.RootPage : ContentReference.StartPage;

        // return any list of valid ACL, for example from Root or StartPage which those settings belong to
        var accessControlList = (_contentLoader.Get<IContent>(aclReference) as PageData)?.ACL;

        return accessControlList?.CreateWritableClone() as IContentSecurityDescriptor;
    }
```

**Comment by LinusEkstrom** [comment]
@wezz Are you able to have a look at Andrews updated reportinfo to see if we can fix the issue that seems to remain?

**Comment by LinusEkstrom** [comment]
@andrewmarkham We have a new build with a fix for the last issue. Unsure if you can access the build directly if you want to verify before I upload, either through an email or directly if you have access https://github.com/LinusEkstrom/AddOn.Episerver.Settings/actions/runs/10401013241

**Comment by andrewmarkham** [comment]
@LinusEkstrom, I can access the artefact, I will test it tomorrow.

**Comment by andrewmarkham** [comment]
Hi @LinusEkstrom,

Just tested and works, thanks :)

**Comment by LinusEkstrom** [comment]
Thanks @andrewmarkham . I've pushed a new version to Optimizelys feed (5.1.4) - should be available soon.
