### ISSUE TITLE
Add support to see if a setting is set on the current page or if it's inherited

### ISSUE THREAD

**Issue by wezz** [LinusEkstrom/AddOn.Episerver.Settings#9]
I would like to be able to see if a setting was actually set on the page that you're on or if it is inherited.
We've had to create extension methods that compares the page's current setting id to the setting id that we got to see if we've inherited the setting or not. 

This could instead be put as a method on the base class for the settings

**Comment by LinusEkstrom** [comment]
I looks like this is being handled in some projects. Is this still a real need that needs to be prioritized @wezz ?

**Comment by LinusEkstrom** [comment]
Closing due to lack of feedback.
